sudo: false
language: cpp
addons:
  apt:
    packages:
    - build-essential
    - g++-4.8
    - clang-3.5
    - wget
    - p7zip-full
    - mono-devel
    - mono-mcs
    - ninja-build
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5
cache:
  directories:
  - $HOME/tools
before_script:
- if [ ! -x ./scripts/setup.sh ]; then chmod +x ./scripts/setup.sh; fi
- ./scripts/setup.sh $HOME
- export PATH=$HOME/tools/bin:$PATH
script:
- premake5 --cc=gcc --arch=x64 --ksp=$PWD/KSP_runtime gmake
- sed -i '/\@echo.*\.cs >> \$(RESPONSE)$/ { s/\\/\//g; }' build/*.make
- CC=gcc-4.8 CXX=g++-4.8 make -j2 -C build/ verbose=1
- mkdir server-build
- cd server-build
- CC=gcc-4.8 CXX=g++-4.8 cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ../
- ninja -v keron
- cp server/keron ../build/Release-x64/bin/
- cd ..
before_deploy:
- cd build/
- tar cjf keron-linux-x64.tar.bz2 Release-x64/
- tar tjf keron-linux-x64.tar.bz2
- cd ../..
deploy:
  provider: releases
  api_key:
    secure: d5YxaCCh3t+CpjVu2oxtA81ASJS5bxynu2omJBiyWwsdaPOaGCOR2bBg4IcBr3Tv/fnAeOHMUHjK1gDhxaF1UHGksjdoauh8McyQ8hHKe4gbFrDntz6HhzKsoV3u7QO918NL3P/DytS3KmjV+DwGe4pCVHJZvYdv30E4kq/tmJI=
  file: $TRAVIS_BUILD_DIR/build/keron-linux-x64.tar.bz2
  draft: true
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: OVyz153fy75n5JFDesZTIUja2dAQh8pEcI1SUc5ppgaUoTCtYx04Oc60kUkm6AbDWfCLB6Z0jOXiLzMVJBgscwEnZRB7saMfA5iBJ5DpZODLJXI+s1VkHcGGIINEVLpB6/vnBZM80biDx7SlF3AC9TwJQCZNZUHE9AUfZAOkIyA=
env:
  secure: hVPhmuTCs5P8YRTXG09bIguI9ZIAYbNJTlNZKJzny4ToUOnqnHKb7eBNQkXpSoUE4+V6Y/lve3nOXg7qzDVqPm33cjaNXdo4s45bMSp+Tv30ZEreJ+lQWS32pEKnglY8EK5u9xZiqRa1S+7+TXatT+OhNOIqaWhx/j5wdrBzPE4=
