version: 1.0.{build}
cache:
- C:\ProgramData\chocolatey\bin -> scripts/client.bat
- C:\ProgramData\chocolatey\lib -> scripts/client.bat
branches:
  only:
  - master
configuration:
  - Debug
  - Release
platform:
  - x86
  - x64
environment:
  archive_pwd:
    secure: /dBxnu4DmsDVzbqPnYSnLGrPZRrrj9w2BNGhxjHaPzTYD1FNs71/h791kE0drs/P
  archive_url:
    secure: w73CoBg7zMyE6aUPAuWFbKfuqzJMtHF9w0Ehe3jL1bQEoh3PD4LMAaS9BZEUEjD7SAjPii7YYE4dQBk57s1FdQ==
  matrix:
  - VS_VERSION: vs2013
  - VS_VERSION: vs2015
notifications:
  - provider: Slack
    auth_token:
      secure: /yDzKEpMQgO35iY7j+jAVUMy+SIk7lXe+JTCSdFM5Ap0tAMI/KcUNqp+dYKAWdj+
    channel: general
install:
  - scripts/setup.bat
  - curl -sSL --insecure -o ksp-runtime.7z %archive_url%
  - 7z x -p%archive_pwd% ksp-runtime.7z
before_build:
  - git submodule init
  - git submodule update
  - del /F /S build
  - premake5.exe --arch=%PLATFORM% --ksp=KSP_runtime %VS_VERSION%
  - dir
  - dir build
  - type build\ENet-net.csproj
  - ps: cat build\ENet-net.csproj | %{$_ -replace "<PropertyGroup>","<PropertyGroup><NoStdLib>true</NoStdLib>"} > build\ENet-net.csproj.new
  - copy build\ENet-net.csproj.new build\ENet-net.csproj
  - type build\ENet-net.csproj
  - type build\client.csproj
  - ps: cat build\client.csproj | %{$_ -replace '\$\(OutDir\)/\.\./bin/flatc','$(SolutionDir)\\$(OutDir)\\..\\bin\\flatc'} > build\client.csproj.new
  - copy build\client.csproj.new build\client.csproj
  - type build\client.csproj
  - tree
build:
  project: build/Keron.sln
  verbosity: normal
after_build:
  - cd ..
  - tree
artifacts:
  - path: build\$(configuration)-$(platform)
    name: keron-win-$(configuration)-$(platform)-$(VS_VERSION)
    type: zip

deploy:
  # Easy merging with Travis which cannot (yet) set a release name...
  release: $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token:
    secure: 57Q/XmAwYwOJfkfUv6axIuO4ZPQsrB3AbjH6ofQki1hLkolCii42C7ZnLYkDn/eY
  artifact: keron-win-$(configuration)-$(platform)-$(VS_VERSION)
  draft: true
  on:
    branch: master
    appveyor_repo_tag: true
    configuration: Release
