version: 1.0.{build}
cache:
- C:\ProgramData\chocolatey\bin -> scripts/client.bat
- C:\ProgramData\chocolatey\lib -> scripts/client.bat
branches:
  only:
  - master
configuration:
  - Debug
  - Release
platform:
  #- Win32
  - x64
environment:
  archive_pwd:
    secure: /dBxnu4DmsDVzbqPnYSnLGrPZRrrj9w2BNGhxjHaPzTYD1FNs71/h791kE0drs/P
  archive_url:
    secure: w73CoBg7zMyE6aUPAuWFbKfuqzJMtHF9w0Ehe3jL1bQEoh3PD4LMAaS9BZEUEjD7SAjPii7YYE4dQBk57s1FdQ==
  matrix:
    #- VS_VERSION: 12 2013
    - VS_VERSION: 14 2015
notifications:
  - provider: Slack
    auth_token:
      secure: /yDzKEpMQgO35iY7j+jAVUMy+SIk7lXe+JTCSdFM5Ap0tAMI/KcUNqp+dYKAWdj+
    channel: general
install:
  - scripts/setup.bat
before_build:
  - git submodule init
  - git submodule update
  - del /F /S build
  - mkdir build
  - cd build
  - if "%PLATFORM%"=="Win32" set GENERATOR="Visual Studio %VS_VERSION%"
  - if "%PLATFORM%"=="x64" set GENERATOR="Visual Studio %VS_VERSION% Win64"
  - cmake -G %GENERATOR% -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DKSP_MANAGED_PATH=%cd%/../KSP_runtime/KSP_Data/Managed ..
  - cd ..
  - dir
  - dir build
  - tree
build:
  project: build/Keron.sln
  verbosity: normal
after_build:
  - cd ..
  - tree
artifacts:
  - path: build\$(configuration)-$(platform)
    name: keron-win-$(configuration)-$(platform)-$(VS_VERSION)
    type: zip

deploy:
  # Easy merging with Travis which cannot (yet) set a release name...
  release: $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token:
    secure: 57Q/XmAwYwOJfkfUv6axIuO4ZPQsrB3AbjH6ofQki1hLkolCii42C7ZnLYkDn/eY
  artifact: keron-win-$(configuration)-$(platform)-$(VS_VERSION)
  draft: true
  on:
    branch: master
    appveyor_repo_tag: true
    configuration: Release
