version: 1.0.{build}
cache:
- C:\ProgramData\chocolatey\bin -> scripts/client.bat
- C:\ProgramData\chocolatey\lib -> scripts/client.bat
branches:
  only:
  - master
configuration:
  - Debug
  - Release
platform:
  - Win32
  - x64
environment:
  archive_pwd:
    secure: /dBxnu4DmsDVzbqPnYSnLGrPZRrrj9w2BNGhxjHaPzTYD1FNs71/h791kE0drs/P
  archive_url:
    secure: w73CoBg7zMyE6aUPAuWFbKfuqzJMtHF9w0Ehe3jL1bQEoh3PD4LMAaS9BZEUEjD7SAjPii7YYE4dQBk57s1FdQ==
  matrix:
    #- VS_VERSION: 12 2013
    - VS_VERSION: 14 2015
notifications:
  - provider: Slack
    auth_token:
      secure: /yDzKEpMQgO35iY7j+jAVUMy+SIk7lXe+JTCSdFM5Ap0tAMI/KcUNqp+dYKAWdj+
    channel: general
install:
  - scripts/install.bat
before_build:
  - scripts/setup.bat
  - dir
  - dir build
  - tree
build:
  parallel: true
  project: build/Keron.sln
  verbosity: normal
after_build:
  - tree
  - msbuild /P:Configuration=%CONFIGURATION% build/PACKAGE.vcxproj
  - copy /B /Y /V build\*.zip build\%CONFIGURATION%-%PLATFORM%.zip
artifacts:
  - path: build\$(configuration)-$(platform)
    name: keron-win-$(configuration)-$(platform)-$(VS_VERSION)
    type: zip

deploy:
  # Easy merging with Travis which cannot (yet) set a release name...
  release: $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token:
    secure: 57Q/XmAwYwOJfkfUv6axIuO4ZPQsrB3AbjH6ofQki1hLkolCii42C7ZnLYkDn/eY
  artifact: keron-win-$(configuration)-$(platform)-$(VS_VERSION)
  draft: true
  on:
    branch: master
    appveyor_repo_tag: true
    configuration: Release
